#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define APP_LED_HEARTBEAT_PERIOD_MS 500U
#define APP_RS485_TEST_BAUDRATE     115200U
#define APP_MODBUS_FRAME_TIMEOUT_MS 5U
#define APP_MODBUS_ADDRESS_APPLY_DELAY_MS 20U
#define APP_MODBUS_ADDRESS_MIN      1U
#define APP_MODBUS_ADDRESS_MAX      7U
#define APP_MODBUS_DEFAULT_ADDRESS  1U
#define APP_MODBUS_REG_SLAVE_ADDRESS 0x0001U

#define APP_CONFIG_FLASH_PAGE_SIZE  FLASH_PAGE_SIZE
#define APP_CONFIG_FLASH_ADDRESS    (0x0800F800UL)
#define APP_CONFIG_FLASH_PAGE_INDEX (APP_CONFIG_FLASH_ADDRESS / APP_CONFIG_FLASH_PAGE_SIZE - (FLASH_BASE / APP_CONFIG_FLASH_PAGE_SIZE))
#define APP_CONFIG_FLASH_MAGIC      0x43464731UL
#define APP_CONFIG_FLASH_VERSION    0x00000001UL

extern const char g_app_rs485_boot_banner[];

#endif /* APP_CONFIG_H */
