#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define APP_LED_HEARTBEAT_PERIOD_MS 500U
#define APP_RS485_TEST_BAUDRATE     115200U
#define APP_RS485_RX_BUFFER_SIZE    64U
#define APP_I2C_SCAN_TIMEOUT_MS     2U
#define APP_I2C_SCAN_READY_TRIALS   2U
#define APP_AI_CHANNEL_COUNT        4U
#define APP_AI_RAW_MAX              4095U
#define APP_AI_SCALED_MAX_MV        10000U
#define APP_AI_INPUT_REG_RAW_BASE   0x0000U
#define APP_AI_INPUT_REG_SCALED_BASE 0x0004U
#define APP_AI_INPUT_REG_COUNT      (APP_AI_CHANNEL_COUNT * 2U)
#define APP_AI_ADS1115_CONVERSION_WAIT_MS 2U
#define APP_AI_ADS1115_I2C_TIMEOUT_MS     3U
#define APP_AI_ADS1115_RETRY_DELAY_MS     20U
/* Tune these if the analog front-end maps 0..10V to a different ADS1115 full-scale point. */
#define APP_AI_ADS1115_POSITIVE_CODE_MAX  32767U
#define APP_AI_CALIBRATED_RAW_AT_10V      1931U
#define APP_AI_ADS1115_PGA_CONFIG         0x0200U
#define APP_STATUS_MODULE_READY_BIT       (1U << 0)
#define APP_STATUS_AI_OVERRANGE_BIT       (1U << 1)
#define APP_ERROR_CODE_NONE               0x0000U
#define APP_ERROR_CODE_AI_ADC_FAULT       0x0001U
#define APP_MODBUS_FRAME_TIMEOUT_MS 5U
#define APP_MODBUS_ADDRESS_APPLY_DELAY_MS 20U
#define APP_MODBUS_ADDRESS_MIN      1U
#define APP_MODBUS_ADDRESS_MAX      7U
#define APP_MODBUS_DEFAULT_ADDRESS  1U
#define APP_MODBUS_REG_SLAVE_ADDRESS 0x0001U

#define APP_CONFIG_FLASH_PAGE_SIZE  FLASH_PAGE_SIZE
#define APP_CONFIG_FLASH_ADDRESS    (0x0800F800UL)
#define APP_CONFIG_FLASH_PAGE_INDEX (APP_CONFIG_FLASH_ADDRESS / APP_CONFIG_FLASH_PAGE_SIZE - (FLASH_BASE / APP_CONFIG_FLASH_PAGE_SIZE))
#define APP_CONFIG_FLASH_MAGIC      0x43464731UL
#define APP_CONFIG_FLASH_VERSION    0x00000001UL

extern const char g_app_rs485_boot_banner[];

#endif /* APP_CONFIG_H */
