set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(DEFINED ENV{STM32CUBECLT_PATH})
    set(_CLT_GNU "$ENV{STM32CUBECLT_PATH}/GNU-tools-for-STM32/bin")
    set(CMAKE_C_COMPILER   "${_CLT_GNU}/arm-none-eabi-gcc.exe")
    set(CMAKE_ASM_COMPILER "${_CLT_GNU}/arm-none-eabi-gcc.exe")
    set(CMAKE_OBJCOPY      "${_CLT_GNU}/arm-none-eabi-objcopy.exe")
    set(CMAKE_SIZE         "${_CLT_GNU}/arm-none-eabi-size.exe")
else()
    find_program(CMAKE_C_COMPILER arm-none-eabi-gcc REQUIRED)
    find_program(CMAKE_ASM_COMPILER arm-none-eabi-gcc REQUIRED)
    find_program(CMAKE_OBJCOPY arm-none-eabi-objcopy REQUIRED)
    find_program(CMAKE_SIZE arm-none-eabi-size REQUIRED)
endif()

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
