#ifndef MODBUS_MAP_H
#define MODBUS_MAP_H

#include <stdint.h>

/*
 * Modbus register map.
 *
 * Input registers:
 * - Public spec data: AI raw and AI scaled
 * - Internal debug data: board raw and ADC code
 *
 * Holding registers:
 * - AO setpoint and mode
 * - Device information and status
 */

#define MODBUS_MAP_AI_CHANNEL_COUNT 4U
#define MODBUS_MAP_AO_CHANNEL_COUNT 4U

/* FC04 input registers: public spec */
#define MODBUS_MAP_INPUT_REG_AI1_RAW       0x0000U
#define MODBUS_MAP_INPUT_REG_AI2_RAW       0x0001U
#define MODBUS_MAP_INPUT_REG_AI3_RAW       0x0002U
#define MODBUS_MAP_INPUT_REG_AI4_RAW       0x0003U
#define MODBUS_MAP_INPUT_REG_AI1_SCALED    0x0004U
#define MODBUS_MAP_INPUT_REG_AI2_SCALED    0x0005U
#define MODBUS_MAP_INPUT_REG_AI3_SCALED    0x0006U
#define MODBUS_MAP_INPUT_REG_AI4_SCALED    0x0007U
#define MODBUS_MAP_INPUT_REG_AI_RAW_BASE   MODBUS_MAP_INPUT_REG_AI1_RAW
#define MODBUS_MAP_INPUT_REG_AI_SCALED_BASE MODBUS_MAP_INPUT_REG_AI1_SCALED
#define MODBUS_MAP_INPUT_REG_PUBLIC_COUNT  (MODBUS_MAP_AI_CHANNEL_COUNT * 2U)

/* FC04 input registers: internal debug */
#define MODBUS_MAP_INPUT_REG_AI1_BOARD_RAW      0x0100U
#define MODBUS_MAP_INPUT_REG_AI2_BOARD_RAW      0x0101U
#define MODBUS_MAP_INPUT_REG_AI3_BOARD_RAW      0x0102U
#define MODBUS_MAP_INPUT_REG_AI4_BOARD_RAW      0x0103U
#define MODBUS_MAP_INPUT_REG_AI1_ADC_CODE       0x0104U
#define MODBUS_MAP_INPUT_REG_AI2_ADC_CODE       0x0105U
#define MODBUS_MAP_INPUT_REG_AI3_ADC_CODE       0x0106U
#define MODBUS_MAP_INPUT_REG_AI4_ADC_CODE       0x0107U
#define MODBUS_MAP_INPUT_REG_AI_BOARD_RAW_BASE  MODBUS_MAP_INPUT_REG_AI1_BOARD_RAW
#define MODBUS_MAP_INPUT_REG_AI_ADC_CODE_BASE   MODBUS_MAP_INPUT_REG_AI1_ADC_CODE
#define MODBUS_MAP_INPUT_REG_DEBUG_COUNT        (MODBUS_MAP_AI_CHANNEL_COUNT * 2U)

/* FC03/FC06/FC16 holding registers: AO control */
#define MODBUS_MAP_HOLDING_REG_AO1_SETPOINT      0x0000U
#define MODBUS_MAP_HOLDING_REG_AO2_SETPOINT      0x0001U
#define MODBUS_MAP_HOLDING_REG_AO3_SETPOINT      0x0002U
#define MODBUS_MAP_HOLDING_REG_AO4_SETPOINT      0x0003U
#define MODBUS_MAP_HOLDING_REG_AO1_MODE          0x0004U
#define MODBUS_MAP_HOLDING_REG_AO2_MODE          0x0005U
#define MODBUS_MAP_HOLDING_REG_AO3_MODE          0x0006U
#define MODBUS_MAP_HOLDING_REG_AO4_MODE          0x0007U
#define MODBUS_MAP_HOLDING_REG_AO_SETPOINT_BASE  MODBUS_MAP_HOLDING_REG_AO1_SETPOINT
#define MODBUS_MAP_HOLDING_REG_AO_MODE_BASE      MODBUS_MAP_HOLDING_REG_AO1_MODE
#define MODBUS_MAP_HOLDING_REG_AO_COUNT          (MODBUS_MAP_AO_CHANNEL_COUNT * 2U)

/* FC03/FC06 holding registers: device information */
#define MODBUS_MAP_HOLDING_REG_DEVICE_ID         0x0008U
#define MODBUS_MAP_HOLDING_REG_FW_VERSION        0x0009U
#define MODBUS_MAP_HOLDING_REG_STATUS            0x000AU
#define MODBUS_MAP_HOLDING_REG_ERROR_CODE        0x000BU
#define MODBUS_MAP_HOLDING_REG_DEVICE_INFO_COUNT 4U
#define MODBUS_MAP_HOLDING_REG_TOTAL_COUNT       (MODBUS_MAP_HOLDING_REG_AO_COUNT + MODBUS_MAP_HOLDING_REG_DEVICE_INFO_COUNT)

#endif /* MODBUS_MAP_H */
